"""Unit tests for services/pdf_extractor.py — implementing PRD FR-1.4/1.5.

Uses real PDF fixtures generated by tests/fixtures/generate_fixtures.py
(run that script first, or via the pytest fixture below which generates
them automatically if missing)."""

from pathlib import Path

import pytest

from app.services.pdf_extractor import PDFExtractionError, ScannedPDFError, extract_text

FIXTURES_DIR = Path(__file__).parent / "fixtures"


@pytest.fixture(scope="module", autouse=True)
def ensure_fixtures_exist():
    """Generates fixtures on the fly if they aren't already present, so
    `pytest` alone (without a separate manual step) is enough to run this
    suite from a fresh checkout."""
    valid = FIXTURES_DIR / "valid_lecture.pdf"
    scanned = FIXTURES_DIR / "scanned_blank.pdf"
    if not valid.exists() or not scanned.exists():
        from tests.fixtures.generate_fixtures import (
            generate_scanned_blank_pdf,
            generate_valid_lecture_pdf,
        )

        generate_valid_lecture_pdf()
        generate_scanned_blank_pdf()


def test_valid_pdf_extracts_expected_text():
    pdf_bytes = (FIXTURES_DIR / "valid_lecture.pdf").read_bytes()
    text = extract_text(pdf_bytes, min_chars=50)
    assert "Thermodynamics" in text
    assert "entropy" in text


def test_scanned_pdf_raises_scanned_pdf_error():
    """FR-1.5: below-threshold extracted text is treated as a likely
    scanned/image PDF."""
    pdf_bytes = (FIXTURES_DIR / "scanned_blank.pdf").read_bytes()
    with pytest.raises(ScannedPDFError):
        extract_text(pdf_bytes, min_chars=50)


def test_corrupt_bytes_raise_pdf_extraction_error_not_scanned_error():
    """A file that isn't a PDF at all should be distinguished from a
    genuinely-empty-but-valid PDF — different error codes map to different
    user-facing messages (PDF_READ_ERROR vs NO_EXTRACTABLE_TEXT)."""
    garbage_bytes = b"this is not a pdf file at all, just plain bytes"
    with pytest.raises(PDFExtractionError):
        extract_text(garbage_bytes, min_chars=50)


def test_boundary_exact_min_chars_is_accepted():
    """Off-by-one check: text exactly at the threshold should pass, per
    the '>= min_chars' comparison in extract_text."""
    pdf_bytes = (FIXTURES_DIR / "valid_lecture.pdf").read_bytes()
    extracted = extract_text(pdf_bytes, min_chars=1)
    # Sanity: with a threshold of 1 char, the real lecture text clears it.
    assert len(extracted) >= 1


def test_scanned_pdf_passes_with_threshold_of_zero():
    """Confirms the threshold is actually doing the gating — with
    min_chars=0, even the blank scanned PDF's empty string should pass,
    proving the earlier failure was genuinely threshold-driven."""
    pdf_bytes = (FIXTURES_DIR / "scanned_blank.pdf").read_bytes()
    extracted = extract_text(pdf_bytes, min_chars=0)
    assert extracted == ""
